[[DecompUtil]]
arch = "aarch64"
git-tree-sha1 = "ff8960bd309ca828174bd8a7300fb58876a548cd"
os = "macos"

    [[DecompUtil.download]]
    sha256 = "4c7ec8211ccb1871c4ba52434305cc30939c40e499903ee77d32a32f83136197"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.aarch64-apple-darwin.tar.gz"
[[DecompUtil]]
arch = "aarch64"
git-tree-sha1 = "992eae17aa4f7d4b3f4ef1e544a946c890361037"
libc = "glibc"
os = "linux"

    [[DecompUtil.download]]
    sha256 = "84f5ace94ce2ea93342822dccee959f53ce96be3485a2ca82eb2d22c61c060a4"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.aarch64-linux-gnu.tar.gz"
[[DecompUtil]]
arch = "aarch64"
git-tree-sha1 = "9a829cc4f6578fe114698a7240adeb629501cf8d"
libc = "musl"
os = "linux"

    [[DecompUtil.download]]
    sha256 = "8eb93ae82321c0f2f8c0383af5d214fe08550d3e79d6e6876e55a2b65a3d0650"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.aarch64-linux-musl.tar.gz"
[[DecompUtil]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b108ea39556e6712d1ade59884d012aee453bb9"
libc = "glibc"
os = "linux"

    [[DecompUtil.download]]
    sha256 = "926fd67482b88b2e9702e3c327df1eef640fba9d67d4c794de04273bc8129820"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.armv6l-linux-gnueabihf.tar.gz"
[[DecompUtil]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e63b22715454de9a89456deba4006d8d6c58ee9"
libc = "musl"
os = "linux"

    [[DecompUtil.download]]
    sha256 = "cfbfc59c61419c92cf2a148ba985d05a7d48d2437144e9905a9d7c0c9483fb33"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.armv6l-linux-musleabihf.tar.gz"
[[DecompUtil]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "559ebcb4e5cd2bb19fb2b05c7e59830bc1aee0c9"
libc = "glibc"
os = "linux"

    [[DecompUtil.download]]
    sha256 = "91e91f379b2a55dd628900b7637c6d1ef92e71159fe8e9404f3302626135de22"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.armv7l-linux-gnueabihf.tar.gz"
[[DecompUtil]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e5f97eee772a4e11bade20e266bba58ae5e36fd"
libc = "musl"
os = "linux"

    [[DecompUtil.download]]
    sha256 = "13864e3ad4e908b67a0925a969a8816ce9de4fa4ee4bc4ab382971649eb4c5d7"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.armv7l-linux-musleabihf.tar.gz"
[[DecompUtil]]
arch = "i686"
git-tree-sha1 = "3dd9e88b97c0774575358b96069a8ad069dcdedb"
libc = "glibc"
os = "linux"

    [[DecompUtil.download]]
    sha256 = "069c886fd50a510354bbdc17ee91f0b45dd7c66569f292c0e930256674d66193"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.i686-linux-gnu.tar.gz"
[[DecompUtil]]
arch = "i686"
git-tree-sha1 = "ce48a979d1b8b61348147dd196e88719470fa7da"
libc = "musl"
os = "linux"

    [[DecompUtil.download]]
    sha256 = "064720f854d91cccf732d2a695120546c12ea698a4b8f207351167389679a640"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.i686-linux-musl.tar.gz"
[[DecompUtil]]
arch = "i686"
git-tree-sha1 = "29efa8fdc528310bc4e6ee2321724af3e8b84c28"
os = "windows"

    [[DecompUtil.download]]
    sha256 = "67d4190ed71c335a4035c5694d45e312e270cb222a4e01450d52b36a5849f080"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.i686-w64-mingw32.tar.gz"
[[DecompUtil]]
arch = "x86_64"
git-tree-sha1 = "32b0876b8402e99ebb6a9a1ed93cb47218382ec1"
os = "macos"

    [[DecompUtil.download]]
    sha256 = "43b75eefae1b726f99392c39dd62b27e36c944a8a31bc63e53f20bfab07d97ce"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.x86_64-apple-darwin.tar.gz"
[[DecompUtil]]
arch = "x86_64"
git-tree-sha1 = "5fb9bfc46d4622a1704ddde3e7cbfc6a5d18dd0f"
libc = "glibc"
os = "linux"

    [[DecompUtil.download]]
    sha256 = "5d412490da8e51a475e5f31c7b2fd8660729f38732b5d978ac300725d67b8557"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.x86_64-linux-gnu.tar.gz"
[[DecompUtil]]
arch = "x86_64"
git-tree-sha1 = "806f25189419d7fb11fd60d13cbd7b258f9be5f0"
libc = "musl"
os = "linux"

    [[DecompUtil.download]]
    sha256 = "5ed07c6259861d3f62369ae1ef38eb93bc2ac14503fdc66ce0c672bfee90edcf"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.x86_64-linux-musl.tar.gz"
[[DecompUtil]]
arch = "x86_64"
git-tree-sha1 = "38a9b10930a70d98a66cf62dd44221b6f9f7e03f"
os = "freebsd"

    [[DecompUtil.download]]
    sha256 = "124c4dedabe05b402a5b6b52a9aeff87cf72f43b4959d25cd33eacf8aede3d63"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.x86_64-unknown-freebsd.tar.gz"
[[DecompUtil]]
arch = "x86_64"
git-tree-sha1 = "a41270741df62104375d6474f3a352f69de4a158"
os = "windows"

    [[DecompUtil.download]]
    sha256 = "a0365df44dfb1f29baaca4f9526ca84d65bb1f785f3fa8e20c7af423a8e3ac66"
    url = "https://github.com/JuliaBinaryWrappers/DecompUtil_jll.jl/releases/download/DecompUtil-v0.1.2+0/DecompUtil.v0.1.2.x86_64-w64-mingw32.tar.gz"
